---

script_repo: https://github.com/TeHikuMedia/libretime-scripts
script_branch: master
script_dir: /home/{{remote_user}}/media_import

sync_dir: /home/{{remote_user}}/sync
sync_config: "/etc/resilio-sync/config.json"
sunshine_db_dir: "{{sync_dir}}/SunshineRadioDB"
tehiku_db_dir: "{{sync_dir}}/TeHikuRadioDB"

nginx_files_dir: /srv/files/