### PLAYBOOK FOR THE PRODUCTION SERVERS ###


- name: "Launch {{env_type}} {{ project_name }} server"
  hosts: localhost
  serial: "100%"
  vars_files:
    - env_vars/base.yml
    - env_vars/staging.yml
    - env_vars/staging_tehiku.yml
    - env_vars/vault.yml
  vars:
    - server_type: web
  roles:
    - ec2
    - ensure-ec2-running
    - load-balance    
    # - s3
    # - cloudfront    
  tags:
    - "{{env_type}}"
    - launch
    - "launch-{{env_type}}"
    - remote


- name: "Provision {{env_type}} {{ project_name }} server"
  hosts: tag_project_env_server_type_{{ project_name }}_{{env_type}}_web
  serial: "100%"
  remote_user: admin
  become: true
  vars:
    - setup_bitbucket_repo: yes
    - update_apt_cache: yes
    - rebuild_database: no
    - server_type: web
    - host_tag: tag_project_env_server_type_{{project_name}}_{{env_type}}_web
  vars_files:
    - env_vars/base.yml
    - env_vars/staging.yml
    - env_vars/staging_tehiku.yml
    - env_vars/vault.yml
  roles:
    - base
    # - ec2-db
    # - memcached
    # - rabbitmq
  tags:
    - "{{env_type}}"
    - provision
    - provision-"{{env_type}}"
    - web
    - remote

- name: "Deploy {{ project_name }} customisation"
  hosts: tag_project_env_server_type_{{ project_name }}_{{env_type}}_web
  serial: "100%"
  remote_user: admin
  become: true
  vars:
    - update_apt_cache: yes
    - server_type: web
    - host_tag: tag_project_env_server_type_{{project_name}}_{{env_type}}_web
  vars_files:
    - env_vars/base.yml
    - env_vars/staging.yml
    - env_vars/staging_tehiku.yml
    - env_vars/vault.yml
  roles:
    - tehiku-radio
  tags:
    - staging
    - deploy
    - deploy-staging
    - web
    - remote
