---

- name: Copy service for "{{item}}"
  template:
    src: "{{item}}"
    dest: "/etc/systemd/system/{{item}}"

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: "Install and start {{item}} service"
  systemd:
    enabled: yes
    state: started
    name: "{{item}}"
    scope: user