---

# - name: Set timezone for machine
#   become: yes
#   command: "sudo timedatectl set-timezone Etc/Greenwich"
  
# - include: restore_airtime_conf.yml

- include: resilio_sync.yml

- include: install_scripts.yml

