---
ec2_key_pair : libretime
git_repo: https://github.com/TeHikuMedia/libretime
project_name: libretime
ssl_dest_dir: /etc/ssl
aws_region: ap-southeast-2
timezone: Pacific/Auckland

station_name: Te Hiku Radio
maintenance: no

# These are AWS seettings which are static or cant be create programatically via ansible
# hosted_zone_id: Z2DXU3EOYXYT52
# aws_cloudfront_ssl_region: us-east-1
# aws_key_name: tehiku

# availability_zones:
#   - ap-southeast-2a
#   - ap-southeast-2b
#   - ap-southeast-2c
