---

- route53_zone:
    zone: "{{zone_domain_name}}"
    state: present
  register: zone
  tags:
    - route53

- elb_application_lb_info:
    region: "{{aws_region}}"
    names: "{{ project_name }}-{{env_type}}-web"
  register: elb
  tags:
    - route53
    - test

- debug:
    var: elb.load_balancers[0]
- debug:
    var: zone
  
- route53:
    state: create
    zone: "{{zone_domain_name}}."
    record: "{{domain_name}}"
    overwrite: yes
    type: A
    value: "{{elb.load_balancers[0]['dns_name']}}" # get this programaticlly
    alias: yes
    alias_hosted_zone_id: "{{elb.load_balancers[0]['canonical_hosted_zone_id']}}" # can we get this programattically
  tags:
    - route53
  ignore_errors: yes


- elb_application_lb_info:
    region: "{{aws_region}}"
    names: "{{ project_name }}-{{env_type}}-net"
  register: elb
  tags:
    - route53
    - test

- route53:
    state: create
    zone: "{{zone_domain_name}}."
    record: "libreice.{{domain_name}}"
    overwrite: yes
    type: A
    value: "{{elb.load_balancers[0]['dns_name']}}" # get this programaticlly
    alias: yes
    alias_hosted_zone_id: "{{elb.load_balancers[0]['canonical_hosted_zone_id']}}" # can we get this programattically
  tags:
    - route53
  ignore_errors: yes
