---

- name: Install git so we can retrieve app source
  apt:
    name: git
    state: latest
  become: true

- name: Setup the git repo
  become: false
  git:  repo="{{ git_repo }}" 
        dest="{{ project_path }}" 
        version="{{ git_branch }}"
        accept_hostkey=yes
        force=yes
  when: setup_git_repo
  tags: git

- name: Run Libretime install script
  command: "chdir=/home/{{remote_user}}/{{project_name}} sudo /home/{{remote_user}}/{{project_name}}/install -qfiap"
  notify:
    - restart apache2

# - name: Create libretime database
#   become_user: postgres
#   postgresql_db:
#     name: "{{db_name}}"
#     state: present

# - name: Create database user
#   postgresql_user:
#     db: "{{db_name}}"
#     name: "{{db_user_name}}"
#     password: "{{db_user_password}}"
#   become_user: postgres

# - name: Copy the libretime config file
#   become: yes
#   template:
#     src: airtime.conf.j2
#     dest: /etc/airtime/airtime.conf
#   notify:
#     - restart airtime

# - name: Start Lirbetime Services
#   become: yes
#   service:
#     name: "{{item}}"
#     state: started
#   with_items:
#       - airtime-playout
#       - airtime-liquidsoap
#       - airtime_analyzer
#       - airtime-celery
#       - libretime_watch
      #- libretime_import

