---


- name: Add ocaml repo
  command: add-apt-repository ppa:avsm/ppa -y

- name: Install ocaml stuff
  apt:
    name:
      - opam
    state: latest
    update_cache: yes

- name: Initialise opam
  # become: no
  become_user: root
  raw: opam init -a && echo 'done'


- name: Set the ocaml version
  # become: no
  become_user: root
  raw: opam switch create 4.09.0 && echo 'done'
  ignore_errors: yes


- name: Install package dependinces
  apt:
    name:
      - libmad0-dev
      - libmp3lame-dev
      - libfdk-aac-dev
    state: present


- name: Install ocaml depext
  # become: no
  become_user: root
  raw: opam install -y depext && echo Done


- name: Install ocaml deps
  # become: no
  become_user: root
  raw: opam depext -y taglib mad lame vorbis cry samplerate fdkaac faad flac ssl ffmpeg liquidsoap && echo Done

- name: Install ocaml programms
  # become: no
  become_user: root
  raw: opam install -y taglib mad lame vorbis cry samplerate fdkaac faad flac ssl ffmpeg liquidsoap && echo Done
