---

- name: "Updating packages"
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install additional ALSA packages
  apt:
    name:
      - alsa-utils 
      - libasound2-plugins
      - pulseaudio
      - jackd2
      - alsa-utils
      - dbus-x11
    state: latest
    update_cache: yes

# - name: "Check liquidsoap installed for version {{liq_version}}"
#   shell: echo `liquidsoap --version | sed -n '1p' - | sed 's/[A-z]\+//'`
#   register: liqout
#   tags:
#     - build
# - set_fact:
#     version: "{{liqout['stdout_lines']}}"
#   tags:
#     - build

# - set_fact:
#     version: "{{version[0]}}"
#   when: version|length > 0
#   tags:
#     - build
# - set_fact:
#     version: 0
#   when: version|length == 0
#   tags:
#     - build

# - debug:
#     msg: "liquipsoap {{version}} exists"
#   tags:
#     - build
#     - liquidsoap
#     - build-liquidsoap

# - name: Install liquidsoap
#   include: liquidsoap.yml
#   when: version != liq_version

- name: Install libretime
  include: libretime.yml

- name: Configure apache2
  include: apache_setup.yml
  tags:
    - apache
