---

- name: "Updating packages"
  apt:
    name: "*"
    state: latest
    update_cache: yes

# - name: "Check liquidsoap installed for version {{liq_version}}"
#   shell: echo `liquidsoap --version | sed -n '1p' - | sed 's/[A-z]\+//'`
#   register: liqout
#   tags:
#     - build
# - set_fact:
#     version: "{{liqout['stdout_lines'][0]}}"
#   tags:
#     - build

# - debug:
#     msg: "liquipsoap {{liq_version}} exists"
#   when: version == liq_version
#   tags:
#     - build
#     - liquidsoap
#     - build-liquidsoap

# - name: Install liquidsoap
#   include: liquidsoap_build.yml
#   when: version != liq_version

- name: Install libretime
  include: libretime.yml

- name: Configure apache2
  include: apache_setup.yml
  tags:
    - apache
