---

# - name: Set timezone for machine
#   become: yes
#   command: "sudo timedatectl set-timezone Etc/Greenwich"
  
# - include: restore_airtime_conf.yml

# - name: "Updating packages"
#   apt:
#     name: "*"
#     state: latest
#     update_cache: yes

- name: "Install required packages"
  apt:
    name:
      - git
      - python3-setuptools
      - ffmpeg
    state: latest
    update_cache: yes

- include: resilio_sync.yml

- include: install_scripts.yml

- include: nginx.yml
  tags:
    - nginx
