---

- name: Install Nginx
  apt:
    name: nginx
    state: latest
  tags: packages

- name: Create the Nginx configuration file
  template: src=nginx.conf.j2
            dest=/etc/nginx/sites-available/{{ project_name }}
            backup=yes
  notify:
    - reload nginx
    - restart nginx
  tags:
    - sites    


- name: Create the files folder
  file:
    state: directory
    path: "{{nginx_files_dir}}"
    group: www-data
    owner: www-data
    mode: '0755'

- name: Ensure that the default site is disabled
  command: rm /etc/nginx/sites-enabled/default
           removes=/etc/nginx/sites-enabled/default
  notify:
    - reload nginx
    - restart nginx
  tags:
    - sites

- name: Ensure that the site is enabled
  command: ln -s /etc/nginx/sites-available/{{ project_name }}
           /etc/nginx/sites-enabled/{{ project_name }}
           creates=/etc/nginx/sites-enabled/{{ project_name }}
  notify:
    - reload nginx
    - restart nginx
  tags:
    - sites  

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes
  tags:
    - sites  
